spring:
  application:
    name: liquibase-sample
  datasource:
    url: jdbc:h2:file:/data/demo
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  liquibase:
    change-log: /db/changelog/db.changelog.master.yml
  h2:
    console:
      enabled: true
